### PR TITLE
updates list_scenarios_for_plan to ignore scenarios missing projects

### PR DESCRIPTION
**Pull request by strangeties**
changes include:
1) reformatting
2) updates list_scenarios_for_plan to ignore scenarios missing projects

results for http://localhost:8000/planscape-backend/plan/list_scenarios_for_plan/?plan_id=51:
image

prior to commit [0d862c2](https://github.com/OurPlanscape/Planscape/pull/610/commits/0d862c2392364d1039b4b5d60864f02e64a8a1d8), there was a NoneType error.

### CODE REVIEW

**Comment by elsiel23** [comment]
i'm not sure if we'll have this issue in prod. the scenarios without projects are probably data that should be deleted from our system

**Comment by elsiel23** [comment]
let me go in and delete scenarios with this property and then we can figure out what to do w the branch after #606 is submitted!

**Comment by elsiel23** [comment]
In dev, deleted 7 scenarios

planscape=> select * from plan_scenario;
 id | owner_id | project_id |         creation_time         | plan_id |        notes        | status | favorited 
----+----------+------------+-------------------------------+---------+---------------------+--------+-----------
 20 |          |         47 | 2023-02-22 21:43:32.052896+00 |      51 | this is my favorite |      0 | f

**Comment by elsiel23** [comment]
In prod, deleting all scenarios (DELETE 11)

**Comment by strangeties** [comment]
Thanks! I'll close this pr and delete the models2 branch.

**Pull request closed without merging**
