### PR TITLE
Adds Dockerfile for Django, updates requirements.txt

### PR DESCRIPTION
**Pull request by strangeties**
Adds a Dockerfile for the Django component.

This is part of issue #111 .

More documentation in the eng directory file, "Deployment Recipes" (e.g. how to configure settings.py).

### CODE REVIEW

**Comment by riecke** [comment]
Looks like the CI test failed.  You can run locally with (assuming a connection to clearcreek.c.googlers.com:5432 is running):

  python manage.py test "\*test\*.py"

I'm not sure how to fix..

**Comment by riecke** [comment]
Everything else looks fine to me, though!

**Comment by strangeties** [comment]
makes sense - debugging now.

**Review by riecke — APPROVED** [review]
Nice!

**Comment by strangeties** [comment]
yay
thanks for reviewing

**Pull request merged**
