### PR TITLE
Migrate from leaflet-draw to leaflet-geoman

### PR DESCRIPTION
**Pull request by lattemilk**
Functionality is the same, but instead using [leaflet-geoman ](https://github.com/geoman-io/leaflet-geoman).

### CODE REVIEW

**Comment by thequeenofspades** [comment]
Do we still need any of the leaflet draw code or can that be removed?

**Comment by lattemilk** [comment]
The leaflet draw code can be removed, but I have some working code on top of this for disabling overlapping polygons, so I was thinking of removing all the leaflet draw code and uninstalling leaflet-draw once that's done.

**Comment by thequeenofspades** [comment]
Sounds reasonable!

**Review by thequeenofspades — APPROVED** [review]

**Comment by lattemilk** [comment]
JK I can remove leaflet-draw now :P

**Pull request merged**
