### PR TITLE
Create uploaded project area upon generating scenario

### PR DESCRIPTION
**Pull request by lattemilk**
# Changes
* Added createProjectArea() method in PlanService to call backend to create project area
* Invokes call when the user clicks "generate scenario"
* Saves uploaded project areas to the db
* Added tests

### CODE REVIEW

**Comment by thequeenofspades** [comment]
It looks like this is 1) creating the scenario and 2) adding the project area to the config, in that order. Is that the order we want to do things in, or do we need to add the project area to the config before creating the scenario? I thought we need to add project area first because the config is frozen + whatever's in there gets used for the scenario create call.

**Comment by lattemilk** [comment]
> It looks like this is 1) creating the scenario and 2) adding the project area to the config, in that order. Is that the order we want to do things in, or do we need to add the project area to the config before creating the scenario? I thought we need to add project area first because the config is frozen + whatever's in there gets used for the scenario create call.

Good point, I wanted to ask UX what should happen if the user uploads project areas, saves (to the config), but then wants to edit/delete those areas before generating the scenario? The workaround is to only create the uploaded project area right when they decide to generate scenario/run forsys.

**Comment by thequeenofspades** [comment]
Gotcha. That's fine as a workaround, but what I meant here was that I think the actual order of calls should be changed to 1) upload project area 2) create scenario, even if they're both triggered by the user clicking "Generate Scenario."

**Comment by lattemilk** [comment]
done! ptal

**Review by thequeenofspades — APPROVED** [review]

**Pull request merged**
